Repository leovianaf/Vei-do-Oeste, pull requests merged in 2025-02, with the labels that each got.

#16 refactor: Alterando movimentação pra 8 direções e Tiro para Mouse
  Assets/Animation/Player Animation/PlayerAnimatorController.controller
  Assets/Prefab/Player.prefab
  Assets/Scripts/MouseAim.cs
  Assets/Scripts/MouseAim.cs.meta
  Assets/Scripts/PlayerMovement.cs
  Assets/Scripts/Shooter.cs
  ProjectSettings/TagManager.asset
Labels: Personagem

#17 feat: add health bar e alteração script player health
  Assets/Scenes/GameScene.unity
  Assets/Scripts/PlayerHealth.cs
Labels: Personagem, UI

#33 feat: Novo sprite pra mira e correção animações Player
  Assets/Animation/Aim Animator.meta
  Assets/Animation/Aim Animator/AimAnimation.anim
  Assets/Animation/Aim Animator/AimAnimation.anim.meta
  Assets/Animation/Aim Animator/AimAnimator.controller
  Assets/Animation/Aim Animator/AimAnimator.controller.meta
  Assets/Animation/Player Animation/PlayerAnimatorController.controller
  Assets/HUD/Aim.meta
  Assets/HUD/Aim/Aim 1.png
  Assets/HUD/Aim/Aim 1.png.meta
  Assets/HUD/Aim/Aim 2.png
  Assets/HUD/Aim/Aim 2.png.meta
  Assets/HUD/Aim/Aim 3.png
  Assets/HUD/Aim/Aim 3.png.meta
  Assets/Scenes/GameScene.unity
Labels: Bugs, Artes/Sons

#36 refactor: Novo comportamento do esqueletos
  Assets/Prefab/Bala.prefab
  Assets/Prefab/Skelleton_Enemy.prefab
  Assets/Prefab/Skelleton_Enemy_Strong.prefab
  Assets/Scripts/Bullet.cs
  Assets/Scripts/Dialogue.cs
  Assets/Scripts/EnemyCollision.cs
  Assets/Scripts/EnemyHealth.cs
  Assets/Scripts/EnemyMovement.cs
  Assets/Scripts/PlayerMovement.cs
  Assets/Scripts/Shooter.cs
Labels: Inimigo, Mecânica

#40 feat: add alien de nave e esqueleto forte
  Assets/Animation/Enemy Animation/Skeleton Run.anim
  Assets/Animation/Enemy Animation/Skeleton Run.anim.meta
  Assets/Animation/Enemy Animation/Skeleton.controller
  Assets/Animation/Enemy Animation/Skeleton.controller.meta
  Assets/Animation/Enemy Animation/Skeleton_Attack.anim
  Assets/Animation/Enemy Animation/Skeleton_Attack.anim.meta
  Assets/Animation/Enemy Animation/Skeleton_Die.anim
  Assets/Animation/Enemy Animation/Skeleton_Die.anim.meta
  Assets/Animation/Enemy Animation/SpaceAlien Run.anim
  Assets/Animation/Enemy Animation/SpaceAlien Run.anim.meta
  Assets/Animation/Enemy Animation/SpaceAlien.controller
  Assets/Animation/Enemy Animation/SpaceAlien.controller.meta
  Assets/Enemies/Alien Guy/alienguycute-Sheet.png.meta
  Assets/Enemies/Alien Spaceship Asset Pack/Spritesheets/AlienRun.png.meta
  Assets/Enemies/Alien Spaceship Asset Pack/Spritesheets/AlienSpin.png.meta
  Assets/Enemies/Skeleton Sprite Pack/Skeleton/Sprite Sheets/Skeleton Attack.png.meta
  Assets/Enemies/Skeleton Sprite Pack/Skeleton/Sprite Sheets/Skeleton Dead.png.meta
  Assets/Enemies/Skeleton Sprite Pack/Skeleton/Sprite Sheets/Skeleton Hit.png.meta
  Assets/Enemies/Skeleton Sprite Pack/Skeleton/Sprite Sheets/Skeleton Idle.png.meta
  Assets/Enemies/Skeleton Sprite Pack/Skeleton/Sprite Sheets/Skeleton React.png.meta
  Assets/Enemies/Skeleton Sprite Pack/Skeleton/Sprite Sheets/Skeleton Walk.png.meta
  Assets/Prefab/Skeleton.prefab
  Assets/Prefab/Skeleton.prefab.meta
  Assets/Prefab/SpaceAlien.prefab
  Assets/Prefab/SpaceAlien.prefab.meta
  Assets/Scenes/GameScene.unity
  Assets/Scripts/SpaceAlienMovement.cs
  Assets/Scripts/SpaceAlienMovement.cs.meta
Labels: Inimigo, Artes/Sons

#50 fix: Ajuste na vida para apenas slider
  Assets/Scripts/HealItem.cs
  Assets/Scripts/PlayerHealth.cs
Labels: Bugs, UI

#66 docs: Update README.md
  README.md
Labels: Documentação

#70 docs: Atualizando imagens README
  README.md
Labels: Documentação

#69 fix: Balanceamento geral e playtesting
  Assets/Music/2 - Galactic Odyssey.ogg
  Assets/Music/2 - Galactic Odyssey.ogg.meta
  Assets/Prefab/Alien.prefab
  Assets/Prefab/AlienPredator.prefab
  Assets/Scenes/GameScene.unity
  Assets/Scripts/EnemyAlienAttack.cs
  Assets/Scripts/EnemyBullet.cs
  Assets/Scripts/Weapons/Colt_Cosmico.asset
  Assets/Scripts/Weapons/Espingarda.asset
  Assets/Scripts/Weapons/Revolver.asset
  Assets/Scripts/Weapons/Rifle.asset
Labels: Bugs, Mecânica
